### ISSUE TITLE
Enhance Quest NPC dialogue layout

### ISSUE THREAD

**Issue by SamKacer** [Duugu/Sku#108]
Hello, not sure how much control the addon has over how the windows and dialogues are presented, but I will share my idea in the case that this could be implemented.

Before I begin, I wil just address that many players might say they dont care for this, since they dont really read the quest descriptions unless they have to, so they just auto accept quests without reading them and then just read the goals in the quest log. I think playing this way is perfectly fine, but I would like to say that other players like me enjoy reading thequest description and general dialogue with the NPC before accepting the quest as it feels much more immersive and also it is easier to read the description then and there, instead of auto accepting and then opening the quest log, and sifting through to find the quest. So for players like us, this could be a welcome quality of life improvement.

The main issue with the quest dialogue when accepting/ turning in quests to an NPC is that for the initial parts, the menu structure is in a way that the player needs to always do down, right, down, right, down, down, right in order to get to any actual useful information.

There are a couple of ways I can think of that would improve the layout and make it more efficient for navigating and cutting down on noise.

### 1: Remove "close" and "goodbye"

These buttons are pretty much pointless, since 1) they do the same thing and 2) same can be achieved with Esc. Removing them completely would cut down on noise and the container on the same menu level could be flattened to remove one level of unnecessary menu nesting.

### 2: Reorder menu items

If option 1 is not possible, then a different way to improve the layout would be to reorder the menu items, placing "close" and "goodbye" at the end raher than the beginning. Then getting to relevant quest info would just be "right, right, right", which would be much simpler.

### 3: Flatten container/details/subsection

If going with option 2, a further refinement would be to take the menu items which are just containers and flatten them, so the menu structure would go from something like this:

#### menu as is (without applying option 2):
```
close
section 3
    | goodbye
    | subsection
        | ...
```

to something like this

#### original menu flattened:
```
close
goodbye
...
```

Although if option 2 is applied, close and goodbye would be at the end, or if option 1 is applied then they wouldn't be there at all.

**Comment by Duugu** [comment]
Hey, 

Thanks alot for this suggestion.

Let me provide some background on those things:

Why are those menu that "cluttered"?

All those menus that are "hooked" under the Local main menu are representations of actual game windows/panels.
That means, if the quest or vendor panel opens, the contents of those will be shown in the audio menu unter "Local".
There are really a lot of different panels.

To get them into the audio menu, without rebuilding every single of them from a scratch (that will take a lot of time) we decided to use an "automated" solution for now.
What we're doing is, the addon just reads out every single component of those panels (the actual UI widgets, like Buttons, Texts, Container, Items, etc.). Then it just creates representations of those components in the audio menu and maps the audio menu to the actual components.
With that approach I don't have to manually rebuild all those panels (as stated, that will take _a lot_ of time).

As you already realized, the disadvantage of that approach is, that the audio menu just maps what is in the UI. And the developers of WoW of course didn't care if those UI components are in some logical or meaningful order. They just add the Close button first, then the Accept button, and then the Text content (just an example, it's even more cluttered :) ). It just makes no difference for them. As they only need to care on the visual appearance, not on any "logical" order.

Unfortunately, that is an "all or nothing" approach. I either can auto-build the menu for a panel, or fully implement it "by hand". It's not possible to use a mixture of both.

So, what we have right now, is just to make those panels accessible at all. It wasn't meant to be the final solution. And it is already scheduled to be replaced by manually designed menus as you described above.  (https://github.com/Duugu/Sku/issues/68)

However, there are still a lot of things that are not accessible at all.  Due to that, my focus atm is to add/work on those things first. If they are done, I will get back to the things in the Local menu and will update them to some more useful / clearer implementation.

I actually already did that for the bags. Idk when you've started playing, but just 2 weeks ago the bags were using the approach described above too. With containers, sub containers, etc. 
As the bags are used that often, I decided to upgrade them from the "automatic" approach to the mentioned "manual" approach (re-building the menu by hand).
As you most probably already realized, the bags are much more useful now. :)

So, thanks again for you suggestion. It is on the list, and will be done if all more urgent things are complete. :)

**Comment by SamKacer** [comment]
@Duugu thanks for the detailed explanation! That makes a lot of sense. I suspected something like that was likely the case.

Although a little surprised that changing the layout is all or nothing and cant be mixed. I expected you could have some sort of rule that if there is an element that is named "container 3" and has children that it would be flattened. But, perhaps such a mixed solution would be the same or even more effort than just redoing the menu by hand.

Shame just how much effort doing all of this is. Maybe at some point I will be able to chip in. I already started taking a couple of curious peeks at the code. I will see if I am able to look into it more substantively

**Comment by Duugu** [comment]
"I expected you could have some sort of rule that if there is an element that is named "container 3" and has children that it would be flattened."

That already is the case.
You would be surprised seeing the mess that would came out of that without that "cleanup". :P

**Comment by Duugu** [comment]
Implemented
