### ISSUE TITLE
Add a "farm mode" to "Quests > .. .> Target"

### ISSUE THREAD

**Issue by Duugu** [Duugu/Sku#3]
Add a third sub menu to "SkuQuest > ... > Ziele" ([CreateRtWpSubmenu](https://github.com/Duugu/Sku/blob/6ffd666f219eae7b86ed70ff7d89ab19f053bdbb/SkuQuest/Options.lua#L259)) wps desc sorted by last visit, to have wps at the top of the list that the player hasn't visited recently.

**Comment by SamKacer** [comment]
This is very similar to what I had in mind, since an enhancement for these type of quests would really help.

What I had in mind is that whenever player reaches a waypoint for mob/object, it would be marked as visited, which would be displayed when looking through list of nearby waypoints with shift + F9. So, normal entry looks something like this:

```23 meters nightsabre, teldrasil```

and if it was visited it could be like:

```visited 23 meters nightsabre teldrasil```

The placement of "visited" could be in a later position. I was thinking it would be good to be at the beginning, since a player would probably not be interested in a mob/object that was already visited.

I think marking waypoints as visited would only be useful for mobs/objects, since whetehr other types of waypoints were visited isnt important.

Then the player could also have a command for resetting visited status of waypoints for if they think the mobs/objects respawned.

Alternatively, if you are going with the "farm" mode, then I think it would be a useful feature, if when you are in the mode, when you reach your waypoint, it automatically starts route to next closest unvisited waypoint, since that is almost always what the player is going to do next

**Comment by Duugu** [comment]
Thanks! I will keep that in mind.
However, please be aware, that this feature is on low priority. As mentioned, all really important things need to be implemented/solved first, before getting to "quality of life" features like this one. Sorry. :/
